# Загружаем данные о других сервисах с помощью  volumes
volumes:
  redpanda:
  minio:
  zookeeper:
  clickhouse:
  signoz:
  arroyo:
  arroyocheckpoint:
  arroyoartifact:
  arroyobuild:

# Описание сервисов, которые одновременно будут работать
services:
  # Название одного из сервисов
  redpanda:
    container_name: redpanda # Имя контейнера 
    # Образ устанвливаемого контейнера Redpanda (в данном случае можно было написать необходимую версию вместо latest)
    image: redpandadata/redpanda:latest 
    # Выполнение команды start при сборке сервиса с указанием всех необходимых при сборке дополнителных параметров 
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --set redpanda.auto_create_topics_enabled=true
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://10.0.2.22:29092,OUTSIDE://10.0.2.22:9092
    ports: [ "9092:9092", "9094:9094" ]  # Переключаемся с порта 9092 сервера на порт 9092 компьютера
    volumes:  # Хранить данные на постоянке, даже после прекращения цикла жизни контейнера
      - redpanda:/var/lib/redpanda/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:  # Чекаем все ли норм с нашим сервисом
      test: [ "CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1" ]
      interval: 5s
      timeout: 1s
      retries: 30
    restart: on-failure  # При каком статусе перезапускается сервис (в данном случае при падении самого сервиса)

  redpanda-connect:
    container_name: redpanda-connect
    image: redpandadata/connect:latest
    # build: ./redpanda  # Директория в которой содержится необходимый Dockerfile
    command: [ 
      "-w", 
      # "-c", 
      # "/connect.yaml", 
      "-r", 
      "/resources/*.yaml", 
      "streams", 
      "/streams/*/*.yaml", 
      "/streams/*/*/*.yaml" ]
    volumes:
      - ./redpanda/redpanda-connect.yaml:/connect.yaml
      - ./redpanda/resources:/resources
      - ./redpanda/templates:/templates
      - ./redpanda/streams:/streams
      - ./redpanda/storage:/storage
      - /etc/localtime:/etc/localtime:ro
    depends_on:  # Какие сервисы должны были быть запущены до этого
      redpanda:
        condition: service_healthy
    restart: on-failure

  redpanda-console:
    container_name: redpanda-console
    image: redpandadata/console:latest
    volumes:
      - ./redpanda:/etc/redpanda/
    environment:  #  Создание переменной окрудение в данном контейнере
      CONFIG_FILEPATH: /etc/redpanda/redpanda-console.yaml
    ports: [ "8080:8080" ]
    depends_on:
      redpanda:
        condition: service_healthy

  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports: ["8123:8123", "9002:9002"]
    volumes: 
      - "./data:/var/lib/clickhouse"
      # - "./clickhouse:/etc/clickhouse-server"
    environment:
      CLICKHOUSE_USER: myuser
      CLICKHOUSE_PASSWORD: mypassword
    ulimits:
      nofile: 262144